services:
  wordpress:
    image: wordpress:1
    build:
      context: ./requirements/wordpress
    container_name : wordpress
    ports:
      - "9000:9000"
    environment:
      WP_HOST: ${WP_HOST}
      WP_TITLE: ${WP_TITLE}
      WP_URL: ${WP_URL}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_DB_NAME: ${WP_DB_NAME}
      DB_USER: ${DB_USER}
      SEC_USER_NAME: ${SEC_USER_NAME}
      SEC_USER_PASS: ${SEC_USER_PASS}
      SEC_USER_EMAIL: ${SEC_USER_EMAIL}
    depends_on:
      - mariadb
    networks:
        - inceptionNetwork
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - user_db_passwd
      - credentails
    restart : always
  mariadb:
    image: mariadb:1
    build :
      context: ./requirements/mariadb
    container_name : mariadb
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      DB_USER: ${DB_USER}
    ports:
        - "3306:3306"
    restart: always
    networks:
        - inceptionNetwork
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - root_db_passwd
      - user_db_passwd
  nginx:
    image: nginx:1
    build :
      context : ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
        - inceptionNetwork
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart : always
  portainer:
    image: portainer:1
    build:
      context: ./requirements/bonus/portainer
    container_name: portainer
    ports:
      - "9001:9000"
    networks:
      - inceptionNetwork
    volumes:
      - portainer_v:/var/run
      - save_data_port:/portainer
    restart: always
  ftp:
    image: ftp-server:1
    build :
      context : ./requirements/bonus/ftp
    container_name : ftp-server
    ports:
      - "21:21"
      - "3000-3100:3000-3100"
    networks :
      - inceptionNetwork
    depends_on:
        - wordpress
    volumes:
        - wordpress_data:/var/www/html/
    restart : always
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWD: ${FTP_PASSWD}
  redis:
    image: redis:1
    build :
      context: ./requirements/bonus/redis
    container_name : redis
    ports:
      - "6379:6379"
    networks:
      - inceptionNetwork
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html/
    restart : always
  adminer:
    image: adminer:1
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - inceptionNetwork
    depends_on: 
      - mariadb
    restart: always
  static-website :
      image: static-website:1
      build :
        context: ./requirements/bonus/static-website
      container_name: static-website
      ports:
        - "5173:5173"
      restart: always
      networks:
        - inceptionNetwork
networks:
  inceptionNetwork :
      driver: bridge 
volumes:
  wordpress_data:
    driver_opts:
      type: none
      device: /home/amejdoub/data/wp
      o: bind
  db_data:
    driver_opts:
      type: none
      device: /home/amejdoub/data/mariadb
      o: bind
  portainer_v:
    driver_opts:
      type: none
      device: /var/run/
      o: bind
  save_data_port:
    driver_opts:
      type: none
      device: /home/amejdoub/data/portainer
      o: bind

secrets:
  root_db_passwd:
    file: ../secrets/db_root_password.txt
  user_db_passwd:
    file: ../secrets/db_password.txt
  credentails:
    file: ../secrets/credentails.txt
