version: "3.9"

services:
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name : wordpress
    ports:
      - "9000:9000"
    environment:
      WP_HOST: mariadb:3306
      WP_TITLE: inception
      WP_URL: https://amejdoub.42.fr
      WP_ADMIN: anas
      WP_ADMIN_PASSWD: 0001
      WP_ADMIN_EMAIL: anasmejdoub@gmail.com
      WP_DB_NAME: inception
      DB_USER: anas
      DB_PASSWD: 8420
    depends_on:
      - mariadb   
    networks:
        - inceptionNetwork
    volumes:
      - wordpress_data:/var/www/html/
    restart : always
  mariadb:
    build :
      context: ./requirements/mariadb
    container_name : mariadb
    environment:
      WP_HOST: mariadb:3306
      WP_TITLE: inception
      WP_URL: https//:amejdoub.42.fr
      WP_ADMIN: anas
      WP_ADMIN_PASSWD: anas
      WP_ADMIN_EMAIL: anasmejdoub@gmail.com
      WP_DB_NAME: inception
      DB_USER: anas
      DB_PASSWD: 8420
      DB_ROOT_PASSWD: 8420
    ports:
        - "3306:3306"
    restart: always
    networks:
        - inceptionNetwork
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    build :
      context : ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
        - inceptionNetwork
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html/
    restart : always
  ftp:
    build :
      context : ./requirements/bonus/ftp
    container_name : ftp
    ports:
      - "21:21"
      - "3000-3100:3000-3100"
    networks :
      - inceptionNetwork
    depends_on:
        - wordpress
    volumes:
        - wordpress_data:/var/www/html/
    restart : always
        

networks:
  inceptionNetwork :
      driver: bridge 
volumes:
  wordpress_data:
    driver_opts:
      o: bind
      type: none
      device: /home/kali/data/wp
  db_data:
    driver_opts:
      o: bind
      type: none
      device: /home/kali/data/mariadb

