services:
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name : wordpress
    ports:
      - "9000:9000"
    environment:
      WP_HOST: mariadb:3306
      WP_TITLE: inception
      WP_URL: 10.11.248.72
      WP_ADMIN: anas
      WP_ADMIN_PASSWD: anas
      WP_ADMIN_EMAIL: anasmejdoub@gmail.com
      WP_DB_NAME: inception
      DB_USER: anas
      DB_PASSWD: anas
    depends_on:
      - mariadb   
    networks:
        - inceptionNetwork
    volumes:
      - wordpress_data:/var/www/html
    restart : always
  mariadb:
    build :
      context: ./requirements/mariadb
    container_name : mariadb
    environment:
      WP_HOST: mariadb:3306
      WP_TITLE: inception
      WP_URL: 10.11.248.72
      WP_ADMIN: anas
      WP_ADMIN_PASSWD: anas
      WP_ADMIN_EMAIL: anasmejdoub@gmail.com
      WP_DB_NAME: inception
      DB_USER: anas
      DB_PASSWD: anas
      DB_ROOT_PASSWD: anas
    ports:
        - "3306:3306"
    restart: always
    networks:
        - inceptionNetwork
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    image: nginx
    build :
      context : ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
        - inceptionNetwork
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart : always
  portainer:
    build:
      context: ./requirements/bonus/portainer
    container_name: portainer
    ports:
      - "9001:9000"
    networks:
      - inceptionNetwork
    volumes:
      - portainer_v:/var/run
    restart: always
  ftp:
    build :
      context : ./requirements/bonus/ftp
    container_name : ftp-server
    ports:
      - "21:21"
#chown -R www-data:www-data .
      - "3000-3100:3000-3100"
    networks :
      - inceptionNetwork
    depends_on:
        - wordpress
    volumes:
        - wordpress_data:/var/www/html/
    restart : always
    environment:
      FTP_USER: anas
      FTP_PASSWD: anas
  redis:
    build :
      context: ./requirements/bonus/redis
    container_name : redis
    ports:
      - "6379:6379"
    networks:
      - inceptionNetwork
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html/
    restart : always
  adminer:
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - inceptionNetwork
    depends_on: 
      - mariadb
    restart: always
  static-website :
      build :
        context: ./requirements/bonus/static-website
      container_name: static-website
      ports:
        - "5173:5173"
      restart: always
      networks:
        - inceptionNetwork
networks:
  inceptionNetwork :
      driver: bridge 
volumes:
  wordpress_data:
    driver_opts:
      type: none
      device: /home/amejdoub/data/wp
      o: bind
  db_data:
    driver_opts:
      type: none
      device: /home/amejdoub/data/mariadb
      o: bind
  portainer_v:
    driver_opts:
      type: none
      device: /var/run/
      o: bind
