version: "3.9"

services:
  wordpress:                       # Define the web application service
    build:
      context: ./requirements/wordpress      # Path to the Dockerfile
    container_name : wordpress
    ports:
      - "9000:9000"            # Map port 80 in the container to port 8080 on the host
    environment:
      WP_HOST: mariadb:3306
      WP_TITLE: inception
      WP_URL: https//:amejdoub.42.fr
      WP_ADMIN: anas
      WP_ADMIN_PASSWD: 0001
      WP_ADMIN_EMAIL: anasmejdoub@gmail.com
      WP_DB_NAME: inception
      DB_USER: anas
      DB_PASSWD: 8420
    depends_on:
      - mariadb   
    networks:
        - inceptionNetwork
    volumes:
      - type: volume
        source: wordpress_data
        target: /var/www/html
  mariadb:                        # Define the database service
    build :
      context: ./requirements/mariadb   # Use the official MariaDB image
    container_name : mariadb
    environment:
      WP_HOST: mariadb:3306
      WP_TITLE: inception
      WP_URL: https//:amejdoub.42.fr
      WP_ADMIN: anas
      WP_ADMIN_PASSWD: 0001
      WP_ADMIN_EMAIL: anasmejdoub@gmail.com
      WP_DB_NAME: inception
      DB_USER: anas
      DB_PASSWD: 8420
      DB_ROOT_PASSWD: 8420
    ports:
        - "3306:3306"
    restart: always
    networks:
        - inceptionNetwork
      #volumes:
      #db_data: 
  nginx:
    build :
      context : ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
        - inceptionNetwork
    depends_on:
      - wordpress
    volumes:
      - type: volume
        source: wordpress_data
        target: /var/www/html

        
        

networks:
  inceptionNetwork :
      driver: bridge 
volumes:
  wordpress_data:
    driver_opts:
      o: bind
      type: none
      device: /home/kali/data/wp

